version: '0.2'
phases:
  install:
    runtime-versions:
      php: '7.3'
    commands:
      # pre-build custom image/container
      - docker-compose -f docker-compose.unittest.yml build unittest-php73
      # install using integrated composer - NOTE: passthrough env var 'COMPOSER_AUTH'
      - docker-compose -f docker-compose.unittest.yml run --no-deps -e COMPOSER_AUTH unittest-php73 composer update
      # alternatively: install on agent, w/o platform checks
      # - composer update --ignore-platform-reqs --no-progress --no-interaction

  build:
    commands:
      - docker-compose -f docker-compose.unittest.yml up unittest-php73

      # full run including coverage report
      # - docker-compose -f docker-compose.unittest.yml run unittest-php73 vendor/bin/phpunit

  post_build:
    commands:
      # just for safety, cleanup.
      - docker-compose -f docker-compose.unittest.yml stop

reports:
  coverage:
    files:
      - .phpunit/coverage.clover.xml
    file-format: CloverXml

  test-report:
    files:
      - .phpunit/report.junit.xml
    file-format: JunitXml
