version: '3'

services:

  # PHP 8.1 CLI
  unittest-php81:
    profiles: [ "php81" ]
    build:
      context: .
      dockerfile: php81-cli.Dockerfile
    environment:
      XDEBUG_MODE: coverage
      unittest_core_db_mysql_host: unittest-mysql
      unittest_core_db_mysql_user: root
      unittest_core_db_mysql_pass: root
      unittest_core_db_mysql_database: database
      unittest_core_cache_memcached_host: unittest-memcached
      unittest_core_cache_memcached_port: 11211
    command: vendor/bin/phpunit
    working_dir: /usr/var/workspace
    depends_on:
      - unittest-mysql
      - unittest-memcached
    links:
      - unittest-mysql
      - unittest-memcached
      - unittest-smtp
      - unittest-ftp
      - unittest-sftp
      - unittest-s3
    volumes:
      # performance optimization, use 'delegated' for authoritative container view
      # improves performance when writing coverage reports and reduces IO load on host
      - '.:/usr/var/workspace:delegated'

  # Memcached
  unittest-memcached:
    image: memcached:alpine

  unittest-smtp:
    image: mailhog/mailhog

  # FTP
  unittest-ftp:
    image: stilliard/pure-ftpd
    # ports:
    #   - "2122:22"
    tmpfs:
      # tmpfs on main ftpusers dir
      - /home/ftpusers:rw
      - /etc/pure-ftpd/passwd:rw
    environment:
      PUBLICHOST: unittest-ftp
      # user home as subdir of ftpusers tmpfs
      FTP_USER_HOME: /home/ftpusers/unittest-ftp-user
      FTP_USER_NAME: unittest-ftp-user
      FTP_USER_PASS: unittest-ftp-pass

  # SFTP
  unittest-sftp:
    image: atmoz/sftp
    tmpfs:
      # two nested tmpfs needed for it to work:
      - /home/unittest-sftp-user-auth-pw:rw
      - /home/unittest-sftp-user-auth-pw/share:rw
      # generic tmpfs stuff
      - /var/run/sftp:rw
      - /etc/sftp:rw
    # ports:
    #   - "2223:22"
    command:
      - 'unittest-sftp-user-auth-pw:unittest-sftp-user-pass:1001::'

  # Fake S3
  unittest-s3:
    image: camjackson/fake-s3
    tmpfs:
      - /fakes3_root:rw
    networks:
      default:
        aliases:
          # - s3.local
          - fakes3.unittest-s3

  # MySQL/MariaDB
  unittest-mysql:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    tmpfs:
      - /var/lib/mysql:rw
