<?php
namespace codename\core\errorstack;

/**
 * Definition for \codename\core\errorstack
 * @package core
 * @since 2016-04-05
 */
interface errorstackInterface {

    /**
     * Adds a new error to the array of errors in the instance
     * @param string $code
     * @param multitype $detail
     * @return \codename\core\errorstack
     * @access public
     */
    public function addError(string $identifier, string $code, $detail = null) : \codename\core\errorstack;

    /**
     * Adds another errorstack instance (content) to this one
     * @author Kevin Dargel
     * @param \codename\core\errorstack $errorstack
     * @return \codename\core\errorstack
     * @access public
     */
    public function addErrorstack(\codename\core\errorstack $errorstack) : \codename\core\errorstack;

    /**
     * Adds an array of errors generated by an errorstack instance (content) to this one
     * @author Kevin Dargel
     * @param array $errors
     * @return \codename\core\errorstack
     * @access public
     */
    public function addErrors(array $errors) : \codename\core\errorstack;

    /**
     * Returns true if there are no errors in the stack
     * @param array $data
     * @return bool
     * @access public
     */
    public function isSuccess() : bool;

    /**
     * Returns all errors that have been stored in the stack
     * @return array
     * @access public
     */
    public function getErrors() : array;

    /**
     * Resets the errorstack
     */
    public function reset() : \codename\core\errorstack;

}
