<?php

namespace codename\core\errorstack;

use codename\core\errorstack;

/**
 * Definition for \codename\core\errorstack
 * @package core
 * @since 2016-04-05
 */
interface errorstackInterface
{
    /**
     * Adds a new error to the array of errors in the instance
     * @param string $identifier
     * @param string $code
     * @param mixed $detail
     * @return errorstack
     * @access public
     */
    public function addError(string $identifier, string $code, mixed $detail = null): errorstack;

    /**
     * Adds another errorstack instance (content) to this one
     * @param errorstack $errorstack
     * @return errorstack
     * @access public
     */
    public function addErrorstack(errorstack $errorstack): errorstack;

    /**
     * Adds an array of errors generated by an errorstack instance (content) to this one
     * @param array $errors
     * @return errorstack
     * @access public
     */
    public function addErrors(array $errors): errorstack;

    /**
     * Returns true if there are no errors in the stack
     * @return bool
     * @access public
     */
    public function isSuccess(): bool;

    /**
     * Returns all errors that have been stored in the stack
     * @return array
     * @access public
     */
    public function getErrors(): array;

    /**
     * Resets the errorstack
     */
    public function reset(): errorstack;
}
